arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
description: "MQTT-Gateway for SAIC cars like MG5, ZS EV or Marvel R"
name: "SAIC MQTT Gateway (Python)"
image: "saicismartapi/saic-python-mqtt-gateway"
url: "https://github.com/SAIC-iSmart-API/saic-home-assistant-addon"
slug: "saic_python_mqtt_gateway"
stage: "experimental"
version: "latest"
legacy: true
options:
  MQTT:
    MQTT_URI: "tcp://localhost:1883"
    MQTT_USER: ""
    MQTT_PASSWORD: ""
    MQTT_TOPIC: ""
  SAIC:
    SAIC_USER: null
    SAIC_PASSWORD: null
  ABRP:  
    ABRP_USER_TOKEN: ""
    OPENWB_LP_MAP: ""
schema:
  MQTT:
    MQTT_URI: str
    MQTT_USER: str?
    MQTT_PASSWORD: password?
    MQTT_TOPIC: str?
  SAIC:
    SAIC_USER: str
    SAIC_PASSWORD: password
  ABRP:
    ABRP_USER_TOKEN: str?
    OPENWB_LP_MAP: str?
init: false
host_network: true
